{% set name = "pyiron_ontology" %}
{% set version = "0.1.0" %}
{% set sha256 = "2bf17d200e7609d04cd37fc1dba130ed22bcddfbeb5518fd3f6794c7cfa578b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_ontology-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - openjdk
    - owlready2
    - pandas
    - pint
    - pyiron_atomistics

test:
  imports:
    - pyiron_ontology
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_ontology
  summary: pyiron_ontology - module extension to pyiron.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    pyiron_ontology provides owlready2-based ontologies and tools to leverage them for pyiron projects.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - liamhuber
